### ISSUE TITLE
plotly displays empty graphs in Jupyter lab notebook on Ubuntu 16.06LTS

### ISSUE THREAD

**Issue by dbl001** [giotto-ai/tutorial_mapper#5]
The plots are empty white space.
Could this issue be related?
https://github.com/plotly/plotly.py/issues/452

![Screen Shot 2019-12-25 at 12 14 11 PM](https://user-images.githubusercontent.com/3105499/71450111-18f6aa00-2710-11ea-9fc2-21c7908e8a20.png)

**Comment by lewtun** [comment]
hi @dbl001, assuming that you're running python 3.5+ can you try following the plotly installation instructions for jupyterlab here: https://github.com/plotly/plotly.py ?

**Comment by lewtun** [comment]
I've added some extra setup instructions to the README
